FROM node:24-alpine AS frontend_builder

WORKDIR /app

COPY frontend/package.json \
     frontend/package-lock.json \
     ./

RUN npm ci

COPY frontend ./

RUN npm run build


FROM nginx:1.29-alpine

COPY docker/nginx/prod.conf \
    /etc/nginx/conf.d/default.conf

COPY backend/public \
    /app/public

COPY --from=frontend_builder \
    /app/dist \
    /srv/homeen

EXPOSE 80
